### ISSUE TITLE
Transport endpoint is not connected after td-agent restart

### ISSUE THREAD

**Issue by dkalashnik** [fluent/fluent-logger-python#103]
After restarting of td-agent socket can't be closed properly and fails with the trace:
How to reproduce: Just restart td-agent.

```2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/logging/__init__.py", line 1448, in info
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self.logger.info(msg, *args, **kwargs)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self._log(INFO, msg, args, **kwargs)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self.handle(record)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self.callHandlers(record)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     hdlr.handle(record)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self.emit(record)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/fluent/handler.py", line 187, in emit
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     data)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/fluent/sender.py", line 98, in emit_with_time
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     return self._send(bytes_)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/fluent/sender.py", line 127, in _send
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     return self._send_internal(bytes_)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/fluent/sender.py", line 149, in _send_internal
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self._close()
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/fluent/sender.py", line 200, in _close
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     self.socket.shutdown(socket.SHUT_RDWR)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/socket.py", line 228, in meth
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server     return getattr(self._sock,name)(*args)
2017-12-04 12:11:04,751.751 2165 ERROR oslo_messaging.rpc.server error: [Errno 107] Transport endpoint is not connected```

**Comment by dkalashnik** [comment]
That one change helps:
```diff --git a/fluent/sender.py b/fluent/sender.py
index bb17ff7..a411151 100644
--- a/fluent/sender.py
+++ b/fluent/sender.py
@@ -1,6 +1,7 @@
 # -*- coding: utf-8 -*-

 from __future__ import print_function
+import errno
 import struct
 import socket
 import threading
@@ -197,7 +198,11 @@ class FluentSender(object):

     def _close(self):
         if self.socket:
-            self.socket.shutdown(socket.SHUT_RDWR)
+            try:
+                self.socket.shutdown(socket.SHUT_RDWR)
+            except socket.error as e:
+                if e.errno != errno.ENOTCONN:
+                    raise e
             self.socket.close()
         self.socket = None
```

**Comment by arcivanov** [comment]
I don't know if there is any advantage whatsoever to shutting down socket prior to close. Is it a SO_LINGER concern?

**Comment by arcivanov** [comment]
Nevermind, it's a correct thing to do: https://docs.python.org/3/howto/sockets.html#disconnecting

**Comment by arcivanov** [comment]
fixed in #104

**Comment by arcivanov** [comment]
If the issue comes back again, please reopen.

**Comment by yangmillstheory** [comment]
This might still be an issue.

I have the following stack; I don't exactly know what version of this library I'm running, but I can find out it in a bit.

```
Stack trace
builtins:OSError: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
File "/usr/local/bin/gunicorn", line 11, in <module>
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 202, in run
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 131, in init_process
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 124, in run
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/usr/local/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 1364, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 892, in __init__
File "/usr/local/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 1253, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 152, in get_response
File "/usr/local/lib/python3.6/logging/__init__.py", line 1318, in warning
File "/usr/local/lib/python3.6/logging/__init__.py", line 1442, in _log
File "/usr/local/lib/python3.6/logging/__init__.py", line 1452, in handle
File "/usr/local/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
File "/usr/local/lib/python3.6/logging/__init__.py", line 863, in handle
File "/usr/local/lib/python3.6/site-packages/fluent/handler.py", line 187, in emit
File "/usr/local/lib/python3.6/site-packages/fluent/sender.py", line 98, in emit_with_time
File "/usr/local/lib/python3.6/site-packages/fluent/sender.py", line 127, in _send
File "/usr/local/lib/python3.6/site-packages/fluent/sender.py", line 149, in _send_internal
File "/usr/local/lib/python3.6/site-packages/fluent/sender.py", line 200, in _close
```

I think this is because `_close` tries to trap `socket.error`, but `OSError` is being thrown. But from the [docs](https://docs.python.org/3/library/socket.html#socket-families),

> All errors raise exceptions. The normal exceptions for invalid argument types and out-of-memory conditions can be raised; starting from Python 3.3, errors related to socket or address semantics raise OSError or one of its subclasses (they used to raise socket.error).

We're running our application in a container `FROM python:3.6-slim`. Can we extend the trap to catch `OSError` as well?

**Comment by arcivanov** [comment]
In 3.6 [socket.error is OSError](https://docs.python.org/3/library/socket.html#socket.error) so it can't be an issue. Please try with 0.9.0.

**Comment by yangmillstheory** [comment]
Looks like we were on an older version. We'll give that a shot. Thanks @arcivanov.
